version: '4.27.1'

services:
  app:
    image: 'weather:latest'
    build:
      context: .
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - "9595-9597:8080"
    environment:
      - "API_KEY=${API_KEY}"
    networks:
      - weather-network
  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - weather-network
  grafana:
    image: grafana/grafana-oss:10.3.1
    pull_policy: always
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000-3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
    networks:
      - weather-network
networks:
  weather-network:


